<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="C02F5AFSMD6M" failures="1" tests="6" name="/Users/meghana.r/Desktop/OLA Backup/IdeaProjects/TestNG_Pratice_Program" time="20.57" errors="0" timestamp="2022-10-05T13:30:57 IST">
  <testcase classname="org.Amazon.BeforeAfterMethod.BeforeAfterMethod" name="TC_loginInvalid" time="0.878">
    <failure type="java.lang.AssertionError" message="User Email address is INVALID CASE..  expected [rs.megha91@yahoo.com] but found [rs.megha91@yahoo.co]">
      <![CDATA[java.lang.AssertionError: User Email address is INVALID CASE..  expected [rs.megha91@yahoo.com] but found [rs.megha91@yahoo.co]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.Amazon.BeforeAfterMethod.BeforeAfterMethod.TC_loginInvalid(BeforeAfterMethod.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- TC_loginInvalid -->
  <testcase classname="org.Amazon.BeforeAfterMethod.BeforeAfterMethod" name="TC_login" time="3.223"/>
  <testcase classname="org.Amazon.BeforeAfterMethod.HomeTests" name="TC_verifyTitle" time="0.007"/>
  <testcase classname="org.Annotations.Tests.TestNGAnnotations" name="Test1" time="0.0"/>
  <testcase classname="org.Annotations.Tests.TestNGAnnotations" name="Test2" time="0.0"/>
  <testcase classname="org.Annotations.Tests.TestNGAnnotations" name="Test3" time="0.0"/>
</testsuite> <!-- /Users/meghana.r/Desktop/OLA Backup/IdeaProjects/TestNG_Pratice_Program -->
